// Country metadata fallback for HeroSMS/SMS-Activate country names.
// Generated from local ISO/calling-code metadata; HeroSMS country names remain the source of truth.
const COUNTRY_META = {
  "ae": ["AE", "971"],
  "af": ["AF", "93"],
  "afganistan": ["AF", "93"],
  "afghanistan": ["AF", "93"],
  "ag": ["AG", "1268"],
  "ai": ["AI", "1264"],
  "al": ["AL", "355"],
  "al ittihad al qumuri": ["KM", "269"],
  "al jumhuriyah al arabiyah as suriyah": ["SY", "963"],
  "al jumhuriyah al libnaniyah": ["LB", "961"],
  "al jumhuriyyah al islamiyyah al muritaniyyah": ["MR", "222"],
  "al jumhuriyyah al yamaniyyah": ["YE", "967"],
  "al jumhuriyyah at tunisiyyah": ["TN", "216"],
  "al mamlakah al arabiyyah as su udiyyah": ["SA", "966"],
  "al mamlakah al magribiyah": ["MA", "212"],
  "al mamlakah al urduniyah al hashimiyah": ["JO", "962"],
  "albania": ["AL", "355"],
  "algeria": ["DZ", "213"],
  "algerie": ["DZ", "213"],
  "am": ["AM", "374"],
  "amelika samoa": ["AS", "1684"],
  "american samoa": ["AS", "1684"],
  "amerika samoa": ["AS", "1684"],
  "angola": ["AO", "244"],
  "anguilla": ["AI", "1264"],
  "antigua and barbuda": ["AG", "1268"],
  "antiguabarbuda": ["AG", "1268"],
  "ao": ["AO", "244"],
  "aolepan aorokin majel": ["MH", "692"],
  "aotearoa": ["NZ", "64"],
  "ar": ["AR", "54"],
  "arab republic of egypt": ["EG", "20"],
  "argentina": ["AR", "54"],
  "argentine republic": ["AR", "54"],
  "armenia": ["AM", "374"],
  "aruba": ["AW", "297"],
  "as": ["AS", "1684"],
  "as sumal": ["SO", "252"],
  "at": ["AT", "43"],
  "au": ["AU", "61"],
  "australia": ["AU", "61"],
  "austria": ["AT", "43"],
  "aw": ["AW", "297"],
  "az": ["AZ", "994"],
  "az rbaycan respublikas": ["AZ", "994"],
  "azerbaijan": ["AZ", "994"],
  "ba": ["BA", "387"],
  "bahrain": ["BH", "973"],
  "bailiwick of guernsey": ["GG", "44"],
  "bailiwick of jersey": ["JE", "44"],
  "bailliage de guernesey": ["GG", "44"],
  "bailliage de jerri": ["JE", "44"],
  "bailliage de jersey": ["JE", "44"],
  "bangladesh": ["BD", "880"],
  "barbados": ["BB", "1246"],
  "bb": ["BB", "1246"],
  "bd": ["BD", "880"],
  "be": ["BE", "32"],
  "belarus": ["BY", "375"],
  "belgie": ["BE", "32"],
  "belgien": ["BE", "32"],
  "belgique": ["BE", "32"],
  "belgium": ["BE", "32"],
  "belize": ["BZ", "501"],
  "belorussiya": ["BY", "375"],
  "beluu er a belau": ["PW", "680"],
  "benin": ["BJ", "229"],
  "bermuda": ["BM", "1441"],
  "bf": ["BF", "226"],
  "bg": ["BG", "359"],
  "bh": ["BH", "973"],
  "bharat": ["IN", "91"],
  "bharat ganrajya": ["IN", "91"],
  "bhutan": ["BT", "975"],
  "bi": ["BI", "257"],
  "bielarus": ["BY", "375"],
  "bj": ["BJ", "229"],
  "bm": ["BM", "1441"],
  "bn": ["BN", "673"],
  "bo": ["BO", "591"],
  "bolivarian republic of venezuela": ["VE", "58"],
  "bolivia": ["BO", "591"],
  "bonaire sint eustatius and saba": ["BQ", "599"],
  "bosnia": ["BA", "387"],
  "bosnia and herzegovina": ["BA", "387"],
  "bosnia herzegovina": ["BA", "387"],
  "botswana": ["BW", "267"],
  "br": ["BR", "55"],
  "brasil": ["BR", "55"],
  "brazil": ["BR", "55"],
  "british indian ocean territory": ["IO", "246"],
  "brunei": ["BN", "673"],
  "bs": ["BS", "1242"],
  "bt": ["BT", "975"],
  "bulgaria": ["BG", "359"],
  "buliwya": ["BO", "591"],
  "buliwya mamallaqta": ["BO", "591"],
  "bundesrepublik deutschland": ["DE", "49"],
  "burkina faso": ["BF", "226"],
  "burkinafaso": ["BF", "226"],
  "burundi": ["BI", "257"],
  "bw": ["BW", "267"],
  "by": ["BY", "375"],
  "bz": ["BZ", "501"],
  "ca": ["CA", "1"],
  "cabo verde": ["CV", "238"],
  "caf": ["CF", "236"],
  "cambodia": ["KH", "855"],
  "cameroon": ["CM", "237"],
  "canada": ["CA", "1"],
  "cape verde": ["CV", "238"],
  "capeverde": ["CV", "238"],
  "cayman islands": ["KY", "1345"],
  "caymanislands": ["KY", "1345"],
  "cc": ["CC", "61"],
  "cd": ["CD", "243"],
  "central african republic": ["CF", "236"],
  "ceska republika": ["CZ", "420"],
  "cesko": ["CZ", "420"],
  "cf": ["CF", "236"],
  "cg": ["CG", "242"],
  "ch": ["CH", "41"],
  "chad": ["TD", "235"],
  "chile": ["CL", "56"],
  "china": ["CN", "86"],
  "choson minjujuui inmin konghwaguk": ["KP", "850"],
  "christmas island": ["CX", "61"],
  "ci": ["CI", "225"],
  "ck": ["CK", "682"],
  "cl": ["CL", "56"],
  "cm": ["CM", "237"],
  "cn": ["CN", "86"],
  "co": ["CO", "57"],
  "co operative republic of guyana": ["GY", "592"],
  "cocos keeling islands": ["CC", "61"],
  "collectivite territoriale de saint pierre et miquelon": ["PM", "508"],
  "colombia": ["CO", "57"],
  "commonwealth of dominica": ["DM", "1767"],
  "commonwealth of puerto rico": ["PR", "1787"],
  "commonwealth of the bahamas": ["BS", "1242"],
  "commonwealth of the northern mariana islands": ["MP", "1670"],
  "comoros": ["KM", "269"],
  "cong hoa xa hoi chu nghia viet nam": ["VN", "84"],
  "congo": ["CG", "242"],
  "congo brazzaville": ["CG", "242"],
  "congo kinshasa": ["CD", "243"],
  "cook islands": ["CK", "682"],
  "costa rica": ["CR", "506"],
  "costarica": ["CR", "506"],
  "cr": ["CR", "506"],
  "croatia": ["HR", "385"],
  "cu": ["CU", "53"],
  "cuba": ["CU", "53"],
  "cumhuriyi tocikiston": ["TJ", "992"],
  "curacao": ["CW", "599"],
  "cv": ["CV", "238"],
  "cx": ["CX", "61"],
  "cy": ["CY", "357"],
  "cyprus": ["CY", "357"],
  "cz": ["CZ", "420"],
  "czech": ["CZ", "420"],
  "czech republic": ["CZ", "420"],
  "czechia": ["CZ", "420"],
  "danmark": ["DK", "45"],
  "dawlat al kuwait": ["KW", "965"],
  "dawlat iritriya": ["ER", "291"],
  "dawlat libya": ["LY", "218"],
  "dawlat qatar": ["QA", "974"],
  "dcongo": ["CD", "243"],
  "de": ["DE", "49"],
  "democratic congo": ["CD", "243"],
  "democratic people s republic of korea": ["KP", "850"],
  "democratic republic of sao tome and principe": ["ST", "239"],
  "democratic republic of the congo": ["CD", "243"],
  "democratic republic of timor leste": ["TL", "670"],
  "democratic socialist republic of sri lanka": ["LK", "94"],
  "denmark": ["DK", "45"],
  "departement de mayotte": ["YT", "262"],
  "department of mayotte": ["YT", "262"],
  "dhivehi raajjeyge jumhooriyya": ["MV", "960"],
  "dj": ["DJ", "253"],
  "djibouti": ["DJ", "253"],
  "dk": ["DK", "45"],
  "dm": ["DM", "1767"],
  "do": ["DO", "1809"],
  "dominica": ["DM", "1767"],
  "dominican": ["DO", "1809"],
  "dominican republic": ["DO", "1809"],
  "dominique": ["DM", "1767"],
  "dr congo": ["CD", "243"],
  "drc": ["CD", "243"],
  "dz": ["DZ", "213"],
  "dzayer": ["DZ", "213"],
  "east timor": ["TL", "670"],
  "ec": ["EC", "593"],
  "ecuador": ["EC", "593"],
  "ee": ["EE", "372"],
  "eesti": ["EE", "372"],
  "eesti vabariik": ["EE", "372"],
  "eg": ["EG", "20"],
  "egypt": ["EG", "20"],
  "eh": ["EH", "212"],
  "eire": ["IE", "353"],
  "el salvador": ["SV", "503"],
  "ellada": ["GR", "30"],
  "ellan vannin": ["IM", "44"],
  "england": ["GB", "44"],
  "equatorial guinea": ["GQ", "240"],
  "equatorialguinea": ["GQ", "240"],
  "er": ["ER", "291"],
  "eritrea": ["ER", "291"],
  "ertra": ["ER", "291"],
  "es": ["ES", "34"],
  "estado libre asociado de puerto rico": ["PR", "1787"],
  "estado plurinacional de bolivia": ["BO", "591"],
  "estados unidos mexicanos": ["MX", "52"],
  "estonia": ["EE", "372"],
  "eswatini": ["SZ", "268"],
  "et": ["ET", "251"],
  "ethiopia": ["ET", "251"],
  "f r erne": ["FO", "298"],
  "f royar": ["FO", "298"],
  "falkland islands": ["FK", "500"],
  "faroe islands": ["FO", "298"],
  "faroeislands": ["FO", "298"],
  "federal democratic republic of ethiopia": ["ET", "251"],
  "federal democratic republic of nepal": ["NP", "977"],
  "federal republic of germany": ["DE", "49"],
  "federal republic of nigeria": ["NG", "234"],
  "federal republic of somalia": ["SO", "252"],
  "federated states of micronesia": ["FM", "691"],
  "federation of saint christopher and nevis": ["KN", "1869"],
  "federative republic of brazil": ["BR", "55"],
  "fi": ["FI", "358"],
  "fiji": ["FJ", "679"],
  "fiji ganarajya": ["FJ", "679"],
  "finland": ["FI", "358"],
  "fj": ["FJ", "679"],
  "fk": ["FK", "500"],
  "fm": ["FM", "691"],
  "fo": ["FO", "298"],
  "fr": ["FR", "33"],
  "france": ["FR", "33"],
  "french guiana": ["GF", "594"],
  "french polynesia": ["PF", "689"],
  "french republic": ["FR", "33"],
  "frenchguiana": ["GF", "594"],
  "furstentum liechtenstein": ["LI", "423"],
  "ga": ["GA", "241"],
  "gabon": ["GA", "241"],
  "gabonese republic": ["GA", "241"],
  "gabuuti": ["DJ", "253"],
  "gabuutih ummuuno": ["DJ", "253"],
  "gb": ["GB", "44"],
  "gd": ["GD", "1473"],
  "ge": ["GE", "995"],
  "georgia": ["GE", "995"],
  "germany": ["DE", "49"],
  "gf": ["GF", "594"],
  "gg": ["GG", "44"],
  "gh": ["GH", "233"],
  "ghana": ["GH", "233"],
  "gi": ["GI", "350"],
  "gibraltar": ["GI", "350"],
  "gl": ["GL", "299"],
  "gm": ["GM", "220"],
  "gn": ["GN", "224"],
  "gonoprojatontri bangladesh": ["BD", "880"],
  "gp": ["GP", "590"],
  "gq": ["GQ", "240"],
  "gr": ["GR", "30"],
  "gr nland": ["GL", "299"],
  "grand duche de luxembourg": ["LU", "352"],
  "grand duchy of luxembourg": ["LU", "352"],
  "great britain": ["GB", "44"],
  "greece": ["GR", "30"],
  "greenland": ["GL", "299"],
  "grenada": ["GD", "1473"],
  "gro herzogtum luxemburg": ["LU", "352"],
  "groussherzogtum letzebuerg": ["LU", "352"],
  "gs": ["GS", "500"],
  "gt": ["GT", "502"],
  "gu": ["GU", "1671"],
  "guadeloupe": ["GP", "590"],
  "guahan": ["GU", "1671"],
  "guam": ["GU", "1671"],
  "guatemala": ["GT", "502"],
  "guernsey": ["GG", "44"],
  "guiana": ["GF", "594"],
  "guinea": ["GN", "224"],
  "guinea bissau": ["GW", "245"],
  "guineabissau": ["GW", "245"],
  "guyana": ["GY", "592"],
  "guyane": ["GF", "594"],
  "gw": ["GW", "245"],
  "gwadloup": ["GP", "590"],
  "gy": ["GY", "592"],
  "haiti": ["HT", "509"],
  "hashemite kingdom of jordan": ["JO", "962"],
  "hayastan": ["AM", "374"],
  "hellenic republic": ["GR", "30"],
  "hk": ["HK", "852"],
  "hn": ["HN", "504"],
  "holland": ["NL", "31"],
  "honduras": ["HN", "504"],
  "hong kong": ["HK", "852"],
  "hongkong": ["HK", "852"],
  "hr": ["HR", "385"],
  "hrvatska": ["HR", "385"],
  "ht": ["HT", "509"],
  "hu": ["HU", "36"],
  "hungary": ["HU", "36"],
  "iceland": ["IS", "354"],
  "id": ["ID", "62"],
  "ie": ["IE", "353"],
  "il": ["IL", "972"],
  "ilankai": ["LK", "94"],
  "im": ["IM", "44"],
  "in": ["IN", "91"],
  "independen stet bilong papua niugini": ["PG", "675"],
  "independent state of papua new guinea": ["PG", "675"],
  "independent state of samoa": ["WS", "685"],
  "india": ["IN", "91"],
  "indonesia": ["ID", "62"],
  "io": ["IO", "246"],
  "iq": ["IQ", "964"],
  "ir": ["IR", "98"],
  "iran": ["IR", "98"],
  "iraq": ["IQ", "964"],
  "ireland": ["IE", "353"],
  "iritriya": ["ER", "291"],
  "is": ["IS", "354"],
  "islami jumhuriya eh pakistan": ["PK", "92"],
  "islamic republic of iran": ["IR", "98"],
  "islamic republic of mauritania": ["MR", "222"],
  "islamic republic of pakistan": ["PK", "92"],
  "island": ["IS", "354"],
  "islas malvinas": ["FK", "500"],
  "isle of man": ["IM", "44"],
  "israel": ["IL", "972"],
  "it": ["IT", "39"],
  "italian republic": ["IT", "39"],
  "italy": ["IT", "39"],
  "ityoppya": ["ET", "251"],
  "ivory": ["CI", "225"],
  "ivory coast": ["CI", "225"],
  "ivorycoast": ["CI", "225"],
  "jabuuti": ["DJ", "253"],
  "jamaica": ["JM", "1876"],
  "jamhuri ya kenya": ["KE", "254"],
  "jamhuri ya muungano wa tanzania": ["TZ", "255"],
  "jamhuri ya uganda": ["UG", "256"],
  "jamhuuriyadda federaalka soomaaliya": ["SO", "252"],
  "jamhuuriyadda jabuuti": ["DJ", "253"],
  "japan": ["JP", "81"],
  "je": ["JE", "44"],
  "jersey": ["JE", "44"],
  "jm": ["JM", "1876"],
  "jo": ["JO", "962"],
  "jomhuri ye eslami ye iran": ["IR", "98"],
  "jordan": ["JO", "962"],
  "jp": ["JP", "81"],
  "jumhuriyat as sudan": ["SD", "249"],
  "jumhuriyyat al iraq": ["IQ", "964"],
  "jumhuriyyat as sumal al fideraliyya": ["SO", "252"],
  "k br s": ["CY", "357"],
  "k br s cumhuriyeti": ["CY", "357"],
  "kazakhstan": ["KZ", "76"],
  "ke": ["KE", "254"],
  "keeling islands": ["CC", "61"],
  "kenya": ["KE", "254"],
  "kg": ["KG", "996"],
  "kh": ["KH", "855"],
  "ki": ["KI", "686"],
  "kingdom of bahrain": ["BH", "973"],
  "kingdom of belgium": ["BE", "32"],
  "kingdom of bhutan": ["BT", "975"],
  "kingdom of cambodia": ["KH", "855"],
  "kingdom of denmark": ["DK", "45"],
  "kingdom of lesotho": ["LS", "266"],
  "kingdom of morocco": ["MA", "212"],
  "kingdom of norway": ["NO", "47"],
  "kingdom of saudi arabia": ["SA", "966"],
  "kingdom of spain": ["ES", "34"],
  "kingdom of swaziland": ["SZ", "268"],
  "kingdom of sweden": ["SE", "46"],
  "kingdom of thailand": ["TH", "66"],
  "kiribati": ["KI", "686"],
  "km": ["KM", "269"],
  "kn": ["KN", "1869"],
  "kongeriget danmark": ["DK", "45"],
  "kongeriket noreg": ["NO", "47"],
  "kongeriket norge": ["NO", "47"],
  "konigreich belgien": ["BE", "32"],
  "koninkrijk belgie": ["BE", "32"],
  "konungariket sverige": ["SE", "46"],
  "kosovo": ["XK", "383"],
  "kp": ["KP", "850"],
  "kr": ["KR", "82"],
  "kuki airani": ["CK", "682"],
  "kuwait": ["KW", "965"],
  "kw": ["KW", "965"],
  "ky": ["KY", "1345"],
  "kypros": ["CY", "357"],
  "kyrgyz republic": ["KG", "996"],
  "kyrgyz respublikasy": ["KG", "996"],
  "kyrgyzstan": ["KG", "996"],
  "kz": ["KZ", "76"],
  "la": ["LA", "856"],
  "lao": ["LA", "856"],
  "lao people s democratic republic": ["LA", "856"],
  "laos": ["LA", "856"],
  "latvia": ["LV", "371"],
  "latvijas republika": ["LV", "371"],
  "lb": ["LB", "961"],
  "lc": ["LC", "1758"],
  "lebanese republic": ["LB", "961"],
  "lebanon": ["LB", "961"],
  "lefatshe la botswana": ["BW", "267"],
  "lesotho": ["LS", "266"],
  "li": ["LI", "423"],
  "liberia": ["LR", "231"],
  "libya": ["LY", "218"],
  "libyan": ["LY", "218"],
  "liechtenstein": ["LI", "423"],
  "lietuvos respublika": ["LT", "370"],
  "lithuania": ["LT", "370"],
  "lk": ["LK", "94"],
  "loktantrik ganatantra nepal": ["NP", "977"],
  "lr": ["LR", "231"],
  "ls": ["LS", "266"],
  "lt": ["LT", "370"],
  "lu": ["LU", "352"],
  "luxembourg": ["LU", "352"],
  "lv": ["LV", "371"],
  "ly": ["LY", "218"],
  "ly veldi island": ["IS", "354"],
  "ma": ["MA", "212"],
  "macao": ["MO", "853"],
  "macao special administrative region of the people s republic of china": ["MO", "853"],
  "macau": ["MO", "853"],
  "madagascar": ["MG", "261"],
  "malawi": ["MW", "265"],
  "malaysia": ["MY", "60"],
  "maldive islands": ["MV", "960"],
  "maldives": ["MV", "960"],
  "mali": ["ML", "223"],
  "malo sa oloto tuto atasi o samoa": ["WS", "685"],
  "malta": ["MT", "356"],
  "mamlakat al bahrayn": ["BH", "973"],
  "mann": ["IM", "44"],
  "mannin": ["IM", "44"],
  "marshall islands": ["MH", "692"],
  "martinique": ["MQ", "596"],
  "matanitu ko viti": ["FJ", "679"],
  "mauritania": ["MR", "222"],
  "mauritius": ["MU", "230"],
  "mayotte": ["YT", "262"],
  "mc": ["MC", "377"],
  "md": ["MD", "373"],
  "medinat yisra el": ["IL", "972"],
  "mexicanos": ["MX", "52"],
  "mexico": ["MX", "52"],
  "mg": ["MG", "261"],
  "mh": ["MH", "692"],
  "mk": ["MK", "389"],
  "ml": ["ML", "223"],
  "mn": ["MN", "976"],
  "mo": ["MO", "853"],
  "moldova": ["MD", "373"],
  "monaco": ["MC", "377"],
  "mongolia": ["MN", "976"],
  "montserrat": ["MS", "1664"],
  "morocco": ["MA", "212"],
  "mozambique": ["MZ", "258"],
  "mp": ["MP", "1670"],
  "mq": ["MQ", "596"],
  "mr": ["MR", "222"],
  "ms": ["MS", "1664"],
  "mt": ["MT", "356"],
  "mu": ["MU", "230"],
  "muso oa lesotho": ["LS", "266"],
  "mv": ["MV", "960"],
  "mw": ["MW", "265"],
  "mx": ["MX", "52"],
  "my": ["MY", "60"],
  "mz": ["MZ", "258"],
  "na": ["NA", "264"],
  "naijiria": ["NG", "234"],
  "namibia": ["NA", "264"],
  "namibie": ["NA", "264"],
  "naoero": ["NR", "674"],
  "nation of brunei": ["BN", "673"],
  "nauru": ["NR", "674"],
  "nc": ["NC", "687"],
  "ne": ["NE", "227"],
  "nederland": ["NL", "31"],
  "nepal": ["NP", "977"],
  "netherlands": ["NL", "31"],
  "new caledonia": ["NC", "687"],
  "new zealand": ["NZ", "64"],
  "newcaledonia": ["NC", "687"],
  "newzealand": ["NZ", "64"],
  "nf": ["NF", "672"],
  "ng": ["NG", "234"],
  "ngwane": ["SZ", "268"],
  "ni": ["NI", "505"],
  "nicaragua": ["NI", "505"],
  "niger": ["NE", "227"],
  "nigeria": ["NG", "234"],
  "nihon": ["JP", "81"],
  "nijar": ["NE", "227"],
  "nijeriya": ["NG", "234"],
  "nippon": ["JP", "81"],
  "niue": ["NU", "683"],
  "nl": ["NL", "31"],
  "no": ["NO", "47"],
  "noreg": ["NO", "47"],
  "norfolk island": ["NF", "672"],
  "norge": ["NO", "47"],
  "north korea": ["KP", "850"],
  "north macedonia": ["MK", "389"],
  "northern mariana islands": ["MP", "1670"],
  "northmacedonia": ["MK", "389"],
  "norway": ["NO", "47"],
  "np": ["NP", "977"],
  "nr": ["NR", "674"],
  "nu": ["NU", "683"],
  "nz": ["NZ", "64"],
  "o zbekiston respublikasi": ["UZ", "998"],
  "oesterreich": ["AT", "43"],
  "om": ["OM", "968"],
  "oman": ["OM", "968"],
  "oriental republic of uruguay": ["UY", "598"],
  "osterreich": ["AT", "43"],
  "pa": ["PA", "507"],
  "pakistan": ["PK", "92"],
  "palau": ["PW", "680"],
  "palestine": ["PS", "970"],
  "panama": ["PA", "507"],
  "papua": ["PG", "675"],
  "papua new guinea": ["PG", "675"],
  "paraguay": ["PY", "595"],
  "pe": ["PE", "51"],
  "people s republic of bangladesh": ["BD", "880"],
  "people s republic of china": ["CN", "86"],
  "peru": ["PE", "51"],
  "pf": ["PF", "689"],
  "pg": ["PG", "675"],
  "ph": ["PH", "63"],
  "philippines": ["PH", "63"],
  "pitcairn henderson ducie and oeno islands": ["PN", "64"],
  "pitcairn islands": ["PN", "64"],
  "pk": ["PK", "92"],
  "pl": ["PL", "48"],
  "pleasant island": ["NR", "674"],
  "plurinational state of bolivia": ["BO", "591"],
  "pm": ["PM", "508"],
  "pn": ["PN", "64"],
  "poblacht na heireann": ["IE", "353"],
  "poland": ["PL", "48"],
  "polynesie francaise": ["PF", "689"],
  "porinetia farani": ["PF", "689"],
  "portugal": ["PT", "351"],
  "portuguesa": ["PT", "351"],
  "portuguese republic": ["PT", "351"],
  "pr": ["PR", "1787"],
  "prathet": ["TH", "66"],
  "principality of liechtenstein": ["LI", "423"],
  "principality of monaco": ["MC", "377"],
  "principaute de monaco": ["MC", "377"],
  "pt": ["PT", "351"],
  "publika de an la": ["AO", "244"],
  "puerto rico": ["PR", "1787"],
  "puertorico": ["PR", "1787"],
  "pw": ["PW", "680"],
  "py": ["PY", "595"],
  "qa": ["QA", "974"],
  "qatar": ["QA", "974"],
  "qazaqstan": ["KZ", "76"],
  "qazaqstan respublikas": ["KZ", "76"],
  "ratcha anachak thai": ["TH", "66"],
  "re": ["RE", "262"],
  "regiao administrativa especial de macau da republica popular da china": ["MO", "853"],
  "reino de espana": ["ES", "34"],
  "repiblik ayiti": ["HT", "509"],
  "repiblik sesel": ["SC", "248"],
  "repoblikan i madagasikara": ["MG", "261"],
  "repubblica di san marino": ["SM", "378"],
  "repubblica italiana": ["IT", "39"],
  "repubblika ta malta": ["MT", "356"],
  "republic of armenia": ["AM", "374"],
  "republic of azerbaijan": ["AZ", "994"],
  "republic of belarus": ["BY", "375"],
  "republic of benin": ["BJ", "229"],
  "republic of botswana": ["BW", "267"],
  "republic of bulgaria": ["BG", "359"],
  "republic of burundi": ["BI", "257"],
  "republic of cabo verde": ["CV", "238"],
  "republic of cameroon": ["CM", "237"],
  "republic of chad": ["TD", "235"],
  "republic of chile": ["CL", "56"],
  "republic of china": ["TW", "886"],
  "republic of colombia": ["CO", "57"],
  "republic of costa rica": ["CR", "506"],
  "republic of cote d ivoire": ["CI", "225"],
  "republic of croatia": ["HR", "385"],
  "republic of cuba": ["CU", "53"],
  "republic of cyprus": ["CY", "357"],
  "republic of djibouti": ["DJ", "253"],
  "republic of ecuador": ["EC", "593"],
  "republic of el salvador": ["SV", "503"],
  "republic of equatorial guinea": ["GQ", "240"],
  "republic of estonia": ["EE", "372"],
  "republic of fiji": ["FJ", "679"],
  "republic of finland": ["FI", "358"],
  "republic of guinea": ["GN", "224"],
  "republic of guinea bissau": ["GW", "245"],
  "republic of haiti": ["HT", "509"],
  "republic of honduras": ["HN", "504"],
  "republic of iceland": ["IS", "354"],
  "republic of india": ["IN", "91"],
  "republic of indonesia": ["ID", "62"],
  "republic of iraq": ["IQ", "964"],
  "republic of ireland": ["IE", "353"],
  "republic of kazakhstan": ["KZ", "76"],
  "republic of kenya": ["KE", "254"],
  "republic of kiribati": ["KI", "686"],
  "republic of korea": ["KR", "82"],
  "republic of latvia": ["LV", "371"],
  "republic of liberia": ["LR", "231"],
  "republic of lithuania": ["LT", "370"],
  "republic of macedonia": ["MK", "389"],
  "republic of madagascar": ["MG", "261"],
  "republic of malawi": ["MW", "265"],
  "republic of mali": ["ML", "223"],
  "republic of malta": ["MT", "356"],
  "republic of mauritius": ["MU", "230"],
  "republic of moldova": ["MD", "373"],
  "republic of mozambique": ["MZ", "258"],
  "republic of namibia": ["NA", "264"],
  "republic of nauru": ["NR", "674"],
  "republic of nicaragua": ["NI", "505"],
  "republic of niger": ["NE", "227"],
  "republic of palau": ["PW", "680"],
  "republic of panama": ["PA", "507"],
  "republic of paraguay": ["PY", "595"],
  "republic of peru": ["PE", "51"],
  "republic of poland": ["PL", "48"],
  "republic of rwanda": ["RW", "250"],
  "republic of san marino": ["SM", "378"],
  "republic of senegal": ["SN", "221"],
  "republic of serbia": ["RS", "381"],
  "republic of seychelles": ["SC", "248"],
  "republic of sierra leone": ["SL", "232"],
  "republic of slovenia": ["SI", "386"],
  "republic of south africa": ["ZA", "27"],
  "republic of suriname": ["SR", "597"],
  "republic of tajikistan": ["TJ", "992"],
  "republic of the congo": ["CG", "242"],
  "republic of the gambia": ["GM", "220"],
  "republic of the maldives": ["MV", "960"],
  "republic of the marshall islands": ["MH", "692"],
  "republic of the philippines": ["PH", "63"],
  "republic of the sudan": ["SD", "249"],
  "republic of trinidad and tobago": ["TT", "1868"],
  "republic of tunisia": ["TN", "216"],
  "republic of turkey": ["TR", "90"],
  "republic of uganda": ["UG", "256"],
  "republic of uzbekistan": ["UZ", "998"],
  "republic of vanuatu": ["VU", "678"],
  "republic of zambia": ["ZM", "260"],
  "republic of zimbabwe": ["ZW", "263"],
  "republica argentina": ["AR", "54"],
  "republica bolivariana de venezuela": ["VE", "58"],
  "republica da guine bissau": ["GW", "245"],
  "republica da guine equatorial": ["GQ", "240"],
  "republica de angola": ["AO", "244"],
  "republica de cabo verde": ["CV", "238"],
  "republica de chile": ["CL", "56"],
  "republica de colombia": ["CO", "57"],
  "republica de costa rica": ["CR", "506"],
  "republica de cuba": ["CU", "53"],
  "republica de el salvador": ["SV", "503"],
  "republica de guinea ecuatorial": ["GQ", "240"],
  "republica de honduras": ["HN", "504"],
  "republica de mocambique": ["MZ", "258"],
  "republica de nicaragua": ["NI", "505"],
  "republica de panama": ["PA", "507"],
  "republica del ecuador": ["EC", "593"],
  "republica del paraguay": ["PY", "595"],
  "republica del peru": ["PE", "51"],
  "republica democratica de sao tome e principe": ["ST", "239"],
  "republica democratica de timor leste": ["TL", "670"],
  "republica federativa do brasil": ["BR", "55"],
  "republica moldova": ["MD", "373"],
  "republica oriental del uruguay": ["UY", "598"],
  "republica portuguesa": ["PT", "351"],
  "republiek suriname": ["SR", "597"],
  "republik indonesia": ["ID", "62"],
  "republik singapura": ["SG", "65"],
  "republika demokratika timor leste": ["TL", "670"],
  "republika hrvatska": ["HR", "385"],
  "republika ng pilipinas": ["PH", "63"],
  "republika slovenija": ["SI", "386"],
  "republika srbija": ["RS", "381"],
  "republika y uburundi": ["BI", "257"],
  "republiken finland": ["FI", "358"],
  "republique centrafricaine": ["CF", "236"],
  "republique d haiti": ["HT", "509"],
  "republique de cote d ivoire": ["CI", "225"],
  "republique de djibouti": ["DJ", "253"],
  "republique de guinee": ["GN", "224"],
  "republique de guinee equatoriale": ["GQ", "240"],
  "republique de madagascar": ["MG", "261"],
  "republique de maurice": ["MU", "230"],
  "republique de vanuatu": ["VU", "678"],
  "republique des seychelles": ["SC", "248"],
  "republique du benin": ["BJ", "229"],
  "republique du burundi": ["BI", "257"],
  "republique du cameroun": ["CM", "237"],
  "republique du mali": ["ML", "223"],
  "republique du niger": ["NE", "227"],
  "republique du rwanda": ["RW", "250"],
  "republique du senegal": ["SN", "221"],
  "republique du tchad": ["TD", "235"],
  "republique francaise": ["FR", "33"],
  "republique gabonaise": ["GA", "241"],
  "republique togolaise": ["TG", "228"],
  "repubulika y u rwanda": ["RW", "250"],
  "respublika belarus": ["BY", "375"],
  "respublika kazakhstan": ["KZ", "76"],
  "reunion": ["RE", "262"],
  "ribaberiki kiribati": ["KI", "686"],
  "ripablik blong vanuatu": ["VU", "678"],
  "ripublik naoero": ["NR", "674"],
  "ro": ["RO", "40"],
  "romania": ["RO", "40"],
  "rossiya": ["RU", "7"],
  "rossiyskaya federatsiya": ["RU", "7"],
  "roumania": ["RO", "40"],
  "royaume de belgique": ["BE", "32"],
  "rsa": ["ZA", "27"],
  "ru": ["RU", "7"],
  "rumania": ["RO", "40"],
  "russia": ["RU", "7"],
  "russian federation": ["RU", "7"],
  "rw": ["RW", "250"],
  "rwanda": ["RW", "250"],
  "rzeczpospolita polska": ["PL", "48"],
  "sa": ["SA", "966"],
  "saint helena": ["SH", "290"],
  "saint kitts and nevis": ["KN", "1869"],
  "saint lucia": ["LC", "1758"],
  "saint pierre and miquelon": ["PM", "508"],
  "saint vincent and the grenadines": ["VC", "1784"],
  "saintkitts": ["KN", "1869"],
  "saintlucia": ["LC", "1758"],
  "saintvincentgrenadines": ["VC", "1784"],
  "sakartvelo": ["GE", "995"],
  "saltanat uman": ["OM", "968"],
  "salvador": ["SV", "503"],
  "samoa": ["WS", "685"],
  "samoa amelika": ["AS", "1684"],
  "san marino": ["SM", "378"],
  "sankattan siha na islas marianas": ["MP", "1670"],
  "sao tome and principe": ["ST", "239"],
  "saotome": ["ST", "239"],
  "saotomeandprincipe": ["ST", "239"],
  "sarnam": ["SR", "597"],
  "sathalanalat paxathipatai paxaxon lao": ["LA", "856"],
  "saudi arabia": ["SA", "966"],
  "saudiarabia": ["SA", "966"],
  "sb": ["SB", "677"],
  "sc": ["SC", "248"],
  "schweiz": ["CH", "41"],
  "sd": ["SD", "249"],
  "se": ["SE", "46"],
  "senegal": ["SN", "221"],
  "serbia": ["RS", "381"],
  "seychelles": ["SC", "248"],
  "sg": ["SG", "65"],
  "sh": ["SH", "290"],
  "shqiperi": ["AL", "355"],
  "shqiperia": ["AL", "355"],
  "shqipnia": ["AL", "355"],
  "si": ["SI", "386"],
  "sierra leone": ["SL", "232"],
  "sierraleone": ["SL", "232"],
  "singapore": ["SG", "65"],
  "singapura": ["SG", "65"],
  "sint maarten": ["SX", "1721"],
  "sj": ["SJ", "4779"],
  "sk": ["SK", "421"],
  "sl": ["SL", "232"],
  "slovak republic": ["SK", "421"],
  "slovakia": ["SK", "421"],
  "slovenia": ["SI", "386"],
  "slovenska republika": ["SK", "421"],
  "sm": ["SM", "378"],
  "sn": ["SN", "221"],
  "so": ["SO", "252"],
  "socialist republic of vietnam": ["VN", "84"],
  "solomon islands": ["SB", "677"],
  "solomonislands": ["SB", "677"],
  "somalia": ["SO", "252"],
  "somers isles": ["BM", "1441"],
  "south africa": ["ZA", "27"],
  "south georgia": ["GS", "500"],
  "south georgia and the south sandwich islands": ["GS", "500"],
  "south korea": ["KR", "82"],
  "south sudan": ["SS", "211"],
  "southafrica": ["ZA", "27"],
  "southsudan": ["SS", "211"],
  "spain": ["ES", "34"],
  "sr": ["SR", "597"],
  "sranangron": ["SR", "597"],
  "srbija": ["RS", "381"],
  "sri lanka": ["LK", "94"],
  "srilanka": ["LK", "94"],
  "ss": ["SS", "211"],
  "st": ["ST", "239"],
  "state of eritrea": ["ER", "291"],
  "state of israel": ["IL", "972"],
  "state of kuwait": ["KW", "965"],
  "state of libya": ["LY", "218"],
  "state of palestine": ["PS", "970"],
  "state of qatar": ["QA", "974"],
  "sudan": ["SD", "249"],
  "suid afrika": ["ZA", "27"],
  "suisse": ["CH", "41"],
  "sultanate of oman": ["OM", "968"],
  "suomen tasavalta": ["FI", "358"],
  "suomi": ["FI", "358"],
  "suriname": ["SR", "597"],
  "sv": ["SV", "503"],
  "svalbard and jan mayen": ["SJ", "4779"],
  "svalbard and jan mayen islands": ["SJ", "4779"],
  "svizra": ["CH", "41"],
  "svizzera": ["CH", "41"],
  "swatini": ["SZ", "268"],
  "swaziland": ["SZ", "268"],
  "sweden": ["SE", "46"],
  "swiss confederation": ["CH", "41"],
  "switzerland": ["CH", "41"],
  "sy": ["SY", "963"],
  "syria": ["SY", "963"],
  "syrian": ["SY", "963"],
  "syrian arab republic": ["SY", "963"],
  "sz": ["SZ", "268"],
  "taiwan": ["TW", "886"],
  "tajikistan": ["TJ", "992"],
  "tanezroft tutrimt": ["EH", "212"],
  "tanzania": ["TZ", "255"],
  "tchad": ["TD", "235"],
  "td": ["TD", "235"],
  "teratri of norf k ailen": ["NF", "672"],
  "territoire des iles wallis et futuna": ["WF", "681"],
  "territory of christmas island": ["CX", "61"],
  "territory of norfolk island": ["NF", "672"],
  "territory of the cocos keeling islands": ["CC", "61"],
  "territory of the wallis and futuna islands": ["WF", "681"],
  "teta paraguai": ["PY", "595"],
  "teta volivia": ["BO", "591"],
  "tg": ["TG", "228"],
  "th": ["TH", "66"],
  "thai": ["TH", "66"],
  "thailand": ["TH", "66"],
  "the abode of peace": ["BN", "673"],
  "the bahamas": ["BS", "1242"],
  "the bermudas": ["BM", "1441"],
  "the gambia": ["GM", "220"],
  "the islands of bermuda": ["BM", "1441"],
  "timor leste": ["TL", "670"],
  "timorleste": ["TL", "670"],
  "tj": ["TJ", "992"],
  "tk": ["TK", "690"],
  "tl": ["TL", "670"],
  "tm": ["TM", "993"],
  "tn": ["TN", "216"],
  "to": ["TO", "676"],
  "tocikiston": ["TJ", "992"],
  "togo": ["TG", "228"],
  "togolese": ["TG", "228"],
  "togolese republic": ["TG", "228"],
  "tokelau": ["TK", "690"],
  "tonga": ["TO", "676"],
  "tr": ["TR", "90"],
  "trinidad": ["TT", "1868"],
  "trinidad and tobago": ["TT", "1868"],
  "tt": ["TT", "1868"],
  "tunisia": ["TN", "216"],
  "turkey": ["TR", "90"],
  "turkiye": ["TR", "90"],
  "turkiye cumhuriyeti": ["TR", "90"],
  "turkmenistan": ["TM", "993"],
  "tuvalu": ["TV", "688"],
  "tv": ["TV", "688"],
  "tw": ["TW", "886"],
  "tz": ["TZ", "255"],
  "ua": ["UA", "380"],
  "uae": ["AE", "971"],
  "udzima wa komori": ["KM", "269"],
  "ug": ["UG", "256"],
  "uganda": ["UG", "256"],
  "uk": ["GB", "44"],
  "ukraine": ["UA", "380"],
  "ukrayina": ["UA", "380"],
  "umbuso waseswatini": ["SZ", "268"],
  "union des comores": ["KM", "269"],
  "union of the comoros": ["KM", "269"],
  "united arab emirates": ["AE", "971"],
  "united kingdom": ["GB", "44"],
  "united mexican states": ["MX", "52"],
  "united republic of tanzania": ["TZ", "255"],
  "united states": ["US", "1"],
  "united states of america": ["US", "1"],
  "uruguay": ["UY", "598"],
  "us": ["US", "1"],
  "usa": ["US", "1"],
  "usa virtual": ["US", "1"],
  "uy": ["UY", "598"],
  "uz": ["UZ", "998"],
  "uzbekistan": ["UZ", "998"],
  "vanuatu": ["VU", "678"],
  "vc": ["VC", "1784"],
  "ve": ["VE", "58"],
  "venezuela": ["VE", "58"],
  "vietnam": ["VN", "84"],
  "viti": ["FJ", "679"],
  "vn": ["VN", "84"],
  "vu": ["VU", "678"],
  "wai tu kubuli": ["DM", "1767"],
  "wallis and futuna": ["WF", "681"],
  "western sahara": ["EH", "212"],
  "weswatini": ["SZ", "268"],
  "wf": ["WF", "681"],
  "ws": ["WS", "685"],
  "wuliwya": ["BO", "591"],
  "wuliwya suyu": ["BO", "591"],
  "ye": ["YE", "967"],
  "yemen": ["YE", "967"],
  "yemeni republic": ["YE", "967"],
  "yt": ["YT", "262"],
  "za": ["ZA", "27"],
  "zambia": ["ZM", "260"],
  "zhongguo": ["CN", "86"],
  "zhonghua": ["CN", "86"],
  "zhonghua minguo": ["TW", "886"],
  "zhonghua renmin gongheguo": ["CN", "86"],
  "zimbabwe": ["ZW", "263"],
  "zm": ["ZM", "260"],
  "zw": ["ZW", "263"],
};

const HERO_COUNTRY_BY_ID = {
  0: 'Russia',
  1: 'Ukraine',
  2: 'Kazakhstan',
  3: 'China',
  4: 'Philippines',
  5: 'Myanmar',
  6: 'Indonesia',
  7: 'Malaysia',
  8: 'Kenya',
  9: 'Tanzania',
  10: 'Vietnam',
  11: 'Kyrgyzstan',
  12: 'United States',
  13: 'Israel',
  14: 'Hong Kong',
  15: 'Poland',
  16: 'United Kingdom',
  17: 'Madagascar',
  18: 'Democratic Republic of the Congo',
  19: 'Nigeria',
  20: 'Macau',
  21: 'Egypt',
  22: 'India',
  23: 'Ireland',
  24: 'Cambodia',
  25: 'Laos',
  26: 'Haiti',
  27: 'Ivory Coast',
  28: 'Gambia',
  29: 'Serbia',
  30: 'Yemen',
  31: 'South Africa',
  32: 'Romania',
  33: 'Colombia',
  34: 'Estonia',
  35: 'Azerbaijan',
  36: 'Canada',
  37: 'Morocco',
  38: 'Ghana',
  39: 'Argentina',
  40: 'Uzbekistan',
  41: 'Cameroon',
  42: 'Chad',
  43: 'Germany',
  44: 'Lithuania',
  45: 'Croatia',
  46: 'Sweden',
  47: 'Iraq',
  48: 'Netherlands',
  49: 'Latvia',
  50: 'Austria',
  51: 'Belarus',
  52: 'Thailand',
  53: 'Saudi Arabia',
  54: 'Mexico',
  55: 'Taiwan',
  56: 'Spain',
  57: 'Iran',
  58: 'Algeria',
  59: 'Slovenia',
  60: 'Bangladesh',
  61: 'Senegal',
  62: 'Turkey',
  63: 'Czech Republic',
  64: 'Sri Lanka',
  65: 'Peru',
  66: 'Pakistan',
  67: 'New Zealand',
  68: 'Guinea',
  69: 'Mali',
  70: 'Venezuela',
  71: 'Ethiopia',
  72: 'Mongolia',
  73: 'Brazil',
  74: 'Afghanistan',
  75: 'Uganda',
  76: 'Angola',
  77: 'Cyprus',
  78: 'France',
  79: 'Papua New Guinea',
  80: 'Mozambique',
  81: 'Nepal',
  82: 'Belgium',
  83: 'Bulgaria',
  84: 'Hungary',
  85: 'Moldova',
  86: 'Italy',
  87: 'Paraguay',
  88: 'Honduras',
  89: 'Tunisia',
  90: 'Nicaragua',
  91: 'Timor-Leste',
  92: 'Bolivia',
  93: 'Costa Rica',
  94: 'Guatemala',
  95: 'United Arab Emirates',
  96: 'Zimbabwe',
  97: 'Puerto Rico',
  98: 'Sudan',
  99: 'Togo',
  100: 'Kuwait',
  101: 'El Salvador',
  102: 'Libya',
  103: 'Jamaica',
  104: 'Trinidad and Tobago',
  105: 'Ecuador',
  106: 'Swaziland',
  107: 'Oman',
  108: 'Bosnia and Herzegovina',
  109: 'Dominican Republic',
  110: 'Syria',
  111: 'Qatar',
  112: 'Panama',
  113: 'Cuba',
  114: 'Mauritania',
  115: 'Sierra Leone',
  116: 'Jordan',
  117: 'Portugal',
  118: 'Barbados',
  119: 'Burundi',
  120: 'Benin',
  121: 'Brunei',
  122: 'Bahamas',
  123: 'Botswana',
  124: 'Belize',
  125: 'Central African Republic',
  126: 'Dominica',
  127: 'Grenada',
  128: 'Georgia',
  129: 'Greece',
  130: 'Guinea-Bissau',
  131: 'Guyana',
  132: 'Iceland',
  133: 'Comoros',
  134: 'Saint Kitts and Nevis',
  135: 'Liberia',
  136: 'Lesotho',
  137: 'Malawi',
  138: 'Namibia',
  139: 'Niger',
  140: 'Rwanda',
  141: 'Slovakia',
  142: 'Suriname',
  143: 'Tajikistan',
  144: 'Monaco',
  145: 'Bahrain',
  146: 'Reunion',
  147: 'Zambia',
  148: 'Armenia',
  149: 'Somalia',
  150: 'Republic of the Congo',
  151: 'Chile',
  152: 'Burkina Faso',
  153: 'Lebanon',
  154: 'Gabon',
  155: 'Albania',
  156: 'Uruguay',
  157: 'Mauritius',
  158: 'Bhutan',
  159: 'Maldives',
  160: 'Guadeloupe',
  161: 'Turkmenistan',
  162: 'French Guiana',
  163: 'Finland',
  164: 'Saint Lucia',
  165: 'Luxembourg',
  166: 'Saint Vincent and the Grenadines',
  167: 'Equatorial Guinea',
  168: 'Djibouti',
  169: 'Antigua and Barbuda',
  170: 'Cayman Islands',
  171: 'Montenegro',
  172: 'Denmark',
  173: 'Switzerland',
  174: 'Norway',
  175: 'Australia',
  176: 'Eritrea',
  177: 'South Sudan',
  178: 'Sao Tome and Principe',
  179: 'Aruba',
  180: 'Montserrat',
  181: 'Anguilla',
  183: 'North Macedonia',
  184: 'Seychelles',
  185: 'New Caledonia',
  186: 'Cape Verde',
  187: 'United States',
  189: 'Fiji',
  196: 'Singapore',
  201: 'Gibraltar',
  202: 'Faroe Islands',
  203: 'Kosovo',
  204: 'Niue',
};

function normalizeCountryName(value) {
  return String(value || "")
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function flagFromIso2(iso2) {
  const code = String(iso2 || "").toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return "🌐";
  return [...code].map((char) => String.fromCodePoint(127397 + char.charCodeAt(0))).join("");
}

export function lookupCountryMeta(name) {
  const key = normalizeCountryName(name);
  const item = COUNTRY_META[key];
  if (!item) return null;
  return { iso2: item[0], dial: item[1], flag: flagFromIso2(item[0]) };
}

export function lookupHeroCountryById(id) {
  const numericId = Number(id);
  const name = Number.isFinite(numericId)
    ? HERO_COUNTRY_BY_ID[numericId]
    : null;

  if (!name) return null;

  return {
    id: numericId,
    name,
    ...lookupCountryMeta(name)
  };
}

export { normalizeCountryName };
